name: Build Flutter APK

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # بررسی و گرفتن آخرین نسخه کد
      - uses: actions/checkout@v3

      # نصب Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'

      # رفتن به ریشه پروژه (محل pubspec.yaml)
      - name: Change directory to project root
        run: cd ${{ github.workspace }}

      # نصب وابستگی‌ها
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ github.workspace }}

      # ساخت APK نسخه release
      - name: Build APK
        run: flutter build apk --release
        working-directory: ${{ github.workspace }}

      # آپلود APK به عنوان artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
